- name: install oh-my-zsh
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: get powerline fonts
  git:
    repo: git clone https://github.com/powerline/fonts.git
    dest: "/tmp/setup/fonts"
    depth: "1"

- name: install fonts
  shell:
    cmd: "cd /tmp/setup/fonts && ./install.sh"

- name: get spaceship prompt
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: "{{ lookup('env', 'ZSH_CUSTOM')}}/themes/spaceship-prompt"

- name: setting up zsh with oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{general.local_home}}/.oh-my-zsh"

- name: sym linking spaceship theme
  file:
    src: "{{ lookup('env', 'ZSH_CUSTOM')}}/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "{{ lookup('env', 'ZSH_CUSTOM')}}/themes/themes/spaceship.zsh-theme"
    state: link

- name: install commitizen
  shell:
    cmd: "npm install -g commitizen"

- name: install rust
  shel:
    cmd: "curl https://sh.rustup.rs -sSf | sh"

- name: create workspace directories
  file:
    path: "{{general.local_home}}/workspace"
    state: directory
