"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[git_branch]
symbol = " "

[kubernetes]
disabled = false
format = 'on [⎈ $context\($namespace\)](dimmed green) '

[directory]
truncation_length = 3
truncate_to_repo = true

[golang]
symbol = " "

[nodejs]
symbol = " "
